
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "research-copilot-rag"
version = "0.1.0"
description = "An AI Research Assistant using RAG and Fine-tuned LLMs"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Zohreh Zakeran"}
]

dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
